jwt:
  secret: 44307383710F9C0EEF2FB4C936D6D756

password:
  key: 92A4C9C99966F9EE749826A03AAA6D3D

spring:
  mail:
    password: hwjbwvsvjevitsxd
    username: r.comanne@gmail.com
  datasource:
    url: jdbc:postgresql://localhost:54320/postgres
    platform: postgres
    username: postgres
    password: sbapp
  jpa:
    hibernate:
      ddl-auto: create-drop